version: "2"
services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Vienna'
    volumes:
       - ~/pihole:/etc/pihole/
       - ~/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=Europe/Vienna
      - UMASK_SET=022
    volumes:
      - ~/tv:/tv
      - ~/movies:/movies
      - ~/config/sonarr:/config
      - ~/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ~/config/nzbget:/config
      - ~/downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped

  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ~/config/jellyfin:/config
      - ~/tv:/tv
      - ~/movies:/movies
    ports:
      - 8096:8096
    restart: unless-stopped
