version: "2"
services:

  proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    environment:
      DEFAULT_HOST: default.vhost
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  sonarr:
    image: linuxserver/sonarr
    environment:
      - VIRTUAL_HOST=sonarr.int32.local
      - PUID=1000
      - PGID=0
      - TZ=Europe/Vienna
      - UMASK_SET=022
    volumes:
      - ./tv:/tv
      - ./movies:/movies
      - ./config/sonarr:/config
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - proxy_default
      - default

  nzbget:
    image: linuxserver/nzbget
    environment:
      - VIRTUAL_HOST=nzb.int32.local
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ./config/nzbget:/config
      - ./downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - proxy_default
      - default
      
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - VIRTUAL_HOST=radarr.int32.local
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config/radarr:/config
      - ./movies:/movies #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxy_default
      - default

networks:
  proxy_default: null
